--- 
title: "Analyzing Elk Movement and Location Using GPS Collar Data"
author: "Megan Whetzel"
date: "`r Sys.Date()`"
site: bookdown::bookdown_site
documentclass: book
bibliography: [book.bib, packages.bib]
biblio-style: apalike
link-citations: yes
description: "This is my final project website for Reproducible Science"
---


# Introduction {-}
My project will be looking at elk (*Cervus elaphus*) GPS collar data and hopefully analyzing their movement by utilizing geospatial data such as elevation, habitat type (from NDVI), weather, etc., and comparing it to their locations. I just started my first semester of my Master's degree in January 2021 and I do not currently have any data available for use from my project. 
  
  
  I hope to use this GPS data from MoveBank (a website for publicly available data) as a surrogate for data I collect in the coming two years. I am unsure of my project yet, but know I will be analyzing ungulate (elk, deer (*Odocoileus* spp), and livestock) movement through and usage of wildfire-burned areas. The elk data from MoveBank will allow me to look at a similar ungulate species' movements, as well as prepare me for analyzing my future data; especially if it involves looking at collared wildlife in the state of Utah. 





